# Generated by Django 2.0.7 on 2018-10-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20181008_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media/images/', width_field='width_field'),
        ),
    ]
