# Generated by Django 2.0.7 on 2018-10-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20181009_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ingredient',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
